#!/bin/bash

# Make sure there is one and only one argument
if [ $# != 1 ]; then
  echo "Please enter an argument"
  exit 1
fi

# Check the argument passed
if [ $1 == 'none' ]; then
  startx ./minimal.xinitrc
elif [ $1 == 'xmonad' ]; then
  startx 
else
  echo "Usage ./start arg1"
  exit 1
fi
